### ISSUE TITLE
[Sprint3] Define roadmap api

### ISSUE THREAD

**Issue by ddanddan18** [swsnu/swpp2020-team6#25]
## Progress

- [x] Task5: Get Roadmap details - api: roadmap_id GET
- [x] Task6: 
  - [x] Get comments  - api: roadmap_id GET
  - [x] Post comment - api: comment POST
  - [x] Edit comment - api: comment_id PUT
  - [x] Delete comment - api: comment_id DELETE
- [x] Task7 : Delete the Roadmap - api: roadmap_id DELETE
- [x] Task8: Create new Roadmap - api: roadmap POST
- [x] Task9: Edit Roadmap - api: roadmap_id PUT 

- [x] Like Roadmap
- [x] pin Roadmap
- [x] duplicate Roadmap

**Comment by ddanddan18** [comment]
Tag 관련 변경사항 다시 보고 코드 일괄 변경하기

**Comment by ddanddan18** [comment]
- [ ] testing
