### ISSUE TITLE
[Feature] Roadmap detail page (roadmap 내용, pin/like/dupilcate/edit/delete)

### ISSUE THREAD

**Issue by gina7484** [swsnu/swpp2020-team6#44]
## Description     
Roadmap detail 페이지            
  - 로드맵 내용 가져와서 

  - 보여주기

  - 필요한 버튼들

  - comment input & 목록들 display

***

## Progress

- [x] get roadmap detail (reducer, actions)    
   - [x] testing
- [x] display roadmap contents    
   - [x] testing
- [x] roadmap delete (backend에 보내고 redux state 변경)    
   - [x] testing
- [x] roadmap edit (redirect해주기)    
   - [x] testing

- [x] pin, duplicate, like 관련 backend, frontend spec 정리 (경혜,진아)

- [x] roadmap duplicate (경혜)    
   - [x] testing (경혜)
- [x] roadmap pin    
   - [x] testing
- [x] roadmap like    
   - [x] testing

## Disscusion:
[Design-and-Planning (revised ver)](https://github.com/swsnu/swpp2020-team6/wiki/2.-Design-and-Planning---revision-draft#actions--reducers)

- pin, like 관련 front spec 정리 완료 (볼드표시 되어 있음)

- **duplicate*: edit page로 바로 넘어가게 할지 여부에 따라 spec 달라짐  <--------NEED DISSCUSION

**Comment by yg-moon** [comment]
duplicate 누르면 edit page로 바로 넘어가는거 찬성!

**Comment by gina7484** [comment]
내가 지금 생각하고 있는 방법

방법1)

1. duplicate 누름: POST `/api/roadmap/${기존 roadmap id}` 불리고 새로운 id가지는 roadmap 만들어져서 post된다.

(그냥 create roadmap은 POST `/api/roadmap/`여서 구분됌)

2. edit page로 push

3. confirm 누르면 PUT `/api/roadmap/${duplicate되어서 새로 만들어진 roadmap id}` 불림.

4. confirm 버튼 옆에 `Duplicate without modification.` 만들기 (이름만 다르고 기능은 edit page에서 cancel이랑 똑같음)

장점) Edit page 거의 그대로 사용가능
   - cancel 버튼만 다른 이름으로 바꿀 수 있게 해주면 된다. (버튼 이름을 props로 받아서 보여주는 식으로 하면 될 것 같음)

***

방법2)

1. duplicate 누르면  POST `/api/roadmap/${기존 roadmap id}`  불리는게 아니라 edit page로 push (새 Roadmap 아직 생성 X)

2. confirm 누르면 POST `/api/roadmap/${기존 roadmap id}` 불려서 새로 만들어진 roadmap id}` 불림.

3. confirm 버튼 옆에 `Cancel duplicate` 만들기 (이름만 다르고 기능은 Create page에서 cancel이랑 똑같음)

장점) Create page 거의 그대로 사용가능
   - Confirm 버튼 눌렀을 때 handler랑 cancel 버튼 이름 바꿔줄 수 있게 해주면 된다.
     (Confirm 버튼의 onClick함수로 전달해주는 함수랑 버튼 이름을 props로 받아서 전달해주게 하면 될 것 같음)

**Comment by ddanddan18** [comment]
결국은 duplicate가
- 내걸로 가져온다+tracking
- fork 후 수정

우리 로드맵 서비스가 만들고 공유 > 트래킹관리 이다보니까 후자가 더 맞는거 같고
그래서 방법2가 더 적절한 거 같음!

**Comment by yg-moon** [comment]
방법2가 나은듯.

미리 만들어두고 수정하는 게 만드는 것 보다, confirm 눌렀을 때 한번에 업로드 되는게 흐름상 자연스러운 것 같아!

**Comment by khkim610** [comment]
저도 2가 나아 보이네욤

**Comment by gina7484** [comment]
방법2로 하겠습니다.

원래는 Edit Roadmap 거의 그대로 쓸 수 있을 것 같았는데    
아무래도 고려해줘야 할 점들이 생겨서 그냥 따로 DuplicateRoadmap 컨테이너 만드는 게 편해보임.    
그래야 
- 함수도 props로 넘겨줄 필요없고
- 버튼 이름도 바꾸고 싶으면 바꿀 수 있고


< 달라진 점 / 추가된 점 >
- 주소는 `/roadmap/duplicate` 사용 예정 : 다들 동의하면 duplicate구현하는 사람이 App.js에 추가해주세요.
- contrainer는 edit roadmap 거의 가져오고, confirm handler를 createRoadmap꺼 가져다쓰면 될 듯함.
   (onConfirm때는 createRoadmap꺼 그대로 쓰면 될 것 같아서 추가적인 action이나 reducer 구현 필요없어보임
    -> 구현 과정에서 필요해지면 여기에 comment)

duplicate하면 새로 만들어진 roadmap detail page로 push.
